modLoader = "javafml"
loaderVersion = "[36,)"
license = "MIT License"

[[mods]]
modId = "hlspells"
version = "${file.jarVersion}"
displayName = "HLSpells"
credits = "Credits are on mod's page."
displayURL = "https://www.curseforge.com/minecraft/mc-mods/hlspells"
authors = "Divinity, StrikerRocker"
description = '''
Ever wanted magic in Minecraft but don't want to commit to those over-complicated ritual magic mods? Then welcome to HLSpells, the plug and play somewhat Vanilla + (+) magic mod. Cast a multitude of spells, all the way from a chain of lightning to just instantly taming your new pet.
'''

[[dependencies.hlspells]] #optional
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hlspells]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2, 1.19)"
ordering = "NONE"

[[dependencies.hlspells]]
modId = "curios"
mandatory = false
versionRange = "[1.18.2-5.0.6.3,)"
ordering = "NONE"
